dist:
  - bionic
services:
  - xvfb
  - postgresql
addons:
  chrome: stable
language: ruby
rvm:
  - 2.7.0
before_install:
  - export TZ=America/Chicago
  - nvm install $(cat .nvmrc)
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox
install:
  - psql --version
  - ruby -v
  - node -v
  - npm i -g yarn
  - make update
before_script:
  - cp config/database.yml.travis config/database.yml
  - export RUBYOPT='-W:no-deprecated -W:no-experimental'; bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bin/webpack
script:
  - make lint
  - make test
