dist:
  - bionic
services:
  - xvfb
  - postgresql
addons:
  postgresql: "11.2"
  chrome: stable
  # apt:
  #   packages:
  #   - postgresql-10
  #   - postgresql-client-10
language: ruby
rvm:
  - 2.7.0
env:
  global:
  - PGPORT=5433
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
before_install:
  - export TZ=America/Chicago
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - psql --version
  - nvm install $(cat .nvmrc)
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox
  - gem install bundler
install:
  - ruby -v
  - node -v
  - npm i -g yarn
  - make update
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - export RUBYOPT='-W:no-deprecated -W:no-experimental'; bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bin/webpack
script:
  - make lint
  - make test
