services:
- xvfb
- postgresql
addons:
- postgresql: '11.3'
- chrome: stable
language: ruby
rvm:
- 2.6.4
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ=America/Chicago
- date
- nvm install $(cat .nvmrc)
- wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- rm chromedriver_linux64.zip
- sudo mv -f chromedriver /usr/local/bin/
- sudo chmod +x /usr/local/bin/chromedriver
- google-chrome-stable --headless --no-sandbox
install:
- bundle install
- node -v
- npm i -g yarn
- yarn
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bin/webpack
script:
- make test
