export const EVENT_NAME = {
    NOTICE_SUCCESS: 'NOTICE_SUCCESS',
    NOTICE_WARNING: 'NOTICE_WARNING',
    NOTICE_ERROR: 'NOTICE_ERROR',
    NOTICE_IMMEDIATELY_REMOVE: 'NOTICE_IMMEDIATELY_REMOVE',
};
